export const PERMISSIONS = {
  AUTH: {
    LOGOUT: 'LOGOUT',
  },
  USER: {
    UPDATE_PROFILE: 'UPDATE_PROFILE',
    DELETE_PROFILE: 'DELETE_PROFILE',
    GET_PROFILE: 'GET_PROFILE',
    CHANGE_PASSWORD: 'CHANGE_PASSWORD',
    GET_USER_LIST: 'GET_USER_LIST',
    UPDATE_USER_ROLE: 'UPDATE_USER_ROLE',
    UPDATE_USER_ACTIVE_STATUS: 'UPDATE_USER_ACTIVE_STATUS',
  },
  LIKE: {
    UPDATE_LIKE_STATUS: 'UPDATE_LIKE_STATUS',
    GET_LIKED_MEDIA_LIST: 'GET_LIKED_MEDIA_LIST',
  },
  CONTENT: {
    CREATE_CONTENT: 'CREATE_CONTENT',
    DELETE_CONTENT: 'DELETE_CONTENT',
    UPDATE_CONTENT: 'UPDATE_CONTENT',
    GET_CONTENT_LIST_BY_GENRE: 'GET_CONTENT_LIST_BY_GENRE',
    GET_CONTENT_BY_ID: 'GET_CONTENT_BY_ID',
    GET_MOST_LIKED_CONTENT_LIST: 'GET_MOST_LIKED_CONTENT_LIST',
    GET_TOP_RATED_CONTENT_LIST: 'GET_TOP_RATED_CONTENT_LIST',
    GET_LATEST_RELEASED_CONTENT_LIST: 'GET_LATEST_RELEASED_CONTENT_LIST',
    GET_POPULAR_CONTENT_LIST: 'GET_POPULAR_CONTENT_LIST',
    GET_SEARCHED_CONTENT_LIST: 'GET_SEARCHED_CONTENT_LIST',
    GET_CONTENT_LIST_OF_NAME_AND_ID: 'GET_CONTENT_LIST_OF_NAME_AND_ID',
    INCREASE_CONTENT_VIEWS_COUNT: 'INCREASE_CONTENT_VIEWS_COUNT',
  },
};

export const USER_PERMISSIONS: string[] = [
  // Auth Permissions
  PERMISSIONS.AUTH.LOGOUT,

  // User Permissions
  PERMISSIONS.USER.UPDATE_PROFILE,
  PERMISSIONS.USER.DELETE_PROFILE,
  PERMISSIONS.USER.GET_PROFILE,
  PERMISSIONS.USER.CHANGE_PASSWORD,

  // Like Permissions
  PERMISSIONS.LIKE.GET_LIKED_MEDIA_LIST,
  PERMISSIONS.LIKE.UPDATE_LIKE_STATUS,

  // Content Permission
  PERMISSIONS.CONTENT.GET_CONTENT_BY_ID,
  PERMISSIONS.CONTENT.GET_CONTENT_LIST_BY_GENRE,
  PERMISSIONS.CONTENT.GET_LATEST_RELEASED_CONTENT_LIST,
  PERMISSIONS.CONTENT.GET_MOST_LIKED_CONTENT_LIST,
  PERMISSIONS.CONTENT.GET_POPULAR_CONTENT_LIST,
  PERMISSIONS.CONTENT.GET_SEARCHED_CONTENT_LIST,
  PERMISSIONS.CONTENT.GET_TOP_RATED_CONTENT_LIST,
  PERMISSIONS.CONTENT.INCREASE_CONTENT_VIEWS_COUNT,
];

export const ADMIN_PERMISSIONS: string[] = [
  // All User Permissions
  ...USER_PERMISSIONS,

  // User Permissions
  PERMISSIONS.USER.GET_USER_LIST,
  PERMISSIONS.USER.UPDATE_USER_ACTIVE_STATUS,
  PERMISSIONS.USER.UPDATE_USER_ROLE,

  // Content Permissions
  PERMISSIONS.CONTENT.CREATE_CONTENT,
  PERMISSIONS.CONTENT.DELETE_CONTENT,
  PERMISSIONS.CONTENT.GET_CONTENT_LIST_OF_NAME_AND_ID,
  PERMISSIONS.CONTENT.UPDATE_CONTENT,
];
